#!/bin/sh

# /* ******** netUstad: Network Ustadi (Network Master) *********/
# /* This software is Copyright (C) 2004 by Ozkan KIRIK.        */
# /* Permission is granted to redistribute and modify this      */
# /* software under the terms of the GNU General Public License */
# /* available at http://www.gnu.org/                           */
# /**************************************************************/

cd $work_path

#================
#== Do the job ==
#================
action=`echo $QUERY_STRING | $awk_cmd -F\& '{print $1}'`
case $action in
dynamic)
	echo $action > /usr/local/etc/netustad/netustad.err
	proto=`echo $QUERY_STRING | $awk_cmd -F\& '{print $2}' | $sed_cmd s/proto=//`
	src_ip=`echo $QUERY_STRING | $awk_cmd -F\& '{print $3}' | $sed_cmd s/src_ip=//`
	src_port=`echo $QUERY_STRING | $awk_cmd -F\& '{print $4}' | $sed_cmd s/src_port=//`
	if test "x" = "x$src_port"; then
		src_port=""
	else
		src_port="--sport $src_port"
	fi
	dst_ip=`echo $QUERY_STRING | $awk_cmd -F\& '{print $5}' | $sed_cmd s/dst_ip=//`
	dst_port=`echo $QUERY_STRING | $awk_cmd -F\& '{print $6}' | $sed_cmd s/dst_port=//`
	if test "x" = "x$dst_port"; then
		dst_port=""
	else
		dst_port="--dport $dst_port"
	fi
	map_ip=`echo $QUERY_STRING | $awk_cmd -F\& '{print $7}' | $sed_cmd s/map_ip=//`
	chain=`echo $QUERY_STRING | $awk_cmd -F\& '{print $8}' | $sed_cmd s/chain=//`
	ruleno=`echo $QUERY_STRING | $awk_cmd -F\& '{print $9}' | $sed_cmd s/ruleno=//`
	if test "x$map_ip" = "xMASQUERADE"; then
		$fw_cmd -t nat -R $chain $ruleno -p $proto -s $src_ip $src_port -d $dst_ip $dst_port -j MASQUERADE 2>&1 /usr/local/etc/netustad/netustad.err
	else
		$fw_cmd -t nat -R $chain $ruleno -p $proto -s $src_ip $src_port -d $dst_ip $dst_port -j SNAT --to $map_ip /usr/local/etc/netustad/netustad.err2
	fi
	./nat_table
	;;
static)
	echo $action > /usr/local/etc/netustad/netustad.err
	publichost=`echo $QUERY_STRING | $awk_cmd -F\& '{print $2}' | $sed_cmd s/publichost=//`
	privatehost=`echo $QUERY_STRING | $awk_cmd -F\& '{print $3}' | $sed_cmd s/privatehost=//`
	chain=`echo $QUERY_STRING | $awk_cmd -F\& '{print $4}' | $sed_cmd s/chain=//`
	ruleno=`echo $QUERY_STRING | $awk_cmd -F\& '{print $5}' | $sed_cmd s/ruleno=//`
	$fw_cmd -t nat -R $chain $ruleno -d $publichost -j DNAT --to $privatehost
	$fw_cmd -t nat -R $chain $ruleno -s $privatehost -j SNAT --to $publichost
	./nat_table
	;;
vserver)
	echo $action > /usr/local/etc/netustad/netustad.err
	proto=`echo $QUERY_STRING | $awk_cmd -F\& '{print $2}' | $sed_cmd s/proto=//`
	publichost=`echo $QUERY_STRING | $awk_cmd -F\& '{print $3}' | $sed_cmd s/publichost=//`
	publicport=`echo $QUERY_STRING | $awk_cmd -F\& '{print $4}' | $sed_cmd s/publicport=//`
	privatehost=`echo $QUERY_STRING | $awk_cmd -F\& '{print $5}' | $sed_cmd s/privatehost=//`
	privateport=`echo $QUERY_STRING | $awk_cmd -F\& '{print $6}' | $sed_cmd s/privateport=//`
	chain=`echo $QUERY_STRING | $awk_cmd -F\& '{print $7}' | $sed_cmd s/chain=//`
	ruleno=`echo $QUERY_STRING | $awk_cmd -F\& '{print $8}' | $sed_cmd s/ruleno=//`
	$fw_cmd -t nat -R $chain $ruleno -p $proto -d $publichost --dport $publicport -j DNAT --to $privatehost:$privateport
	./nat_table
	;;
*)
	echo $action > /usr/local/etc/netustad/netustad.err
	
	#==================
	#== Send headers ==
	#==================
	./header

	#================
	#== Print Data ==
	#================
	echo '<script language="JavaScript" type="text/javascript">'
	echo "function nat_del(chain, num, dest) {"
	echo " if (confirm('`$gettext_cmd "NAT"`: '+dest+' `$gettext_cmd "will be deleted. Is it Okay?"`')) window.location='nat_del?chain='+chain+'&num='+num+'"'$'$server_sid"' }"
	echo "function edit_static(chain,num) {alert(\"`$gettext_cmd "Under Contruction"`\")}"
#	echo " publichost=document.getElementById('static_ip').value;"
#	echo " privatehost=document.getElementById('local_ip').value;"
#	echo " if (publichost!='' && privatehost!='') {"
#	echo " 		window.location='nat_edit?static&publichost='+publichost+'&privatehost='+privatehost+'&chain='+chain+'&ruleno='+num+'$"$server_sid"';"
#	echo " } else {"
#	echo "	alert('`$gettext_cmd "Please Fill All Fields"`');"
#	echo " } }"
	echo "function edit_vserver(chain,num) {alert(\"`$gettext_cmd "Under Contruction"`\")}"
#	echo " proto=document.getElementById('proto').value;"
#	echo " publichost=document.getElementById('publichost').value;"
#	echo " publicport=document.getElementById('publicport').value;"
#	echo " privatehost=document.getElementById('privatehost').value;"
#	echo " privateport=document.getElementById('privateport').value;"
#	echo " if (proto!='' && publichost!='' && privatehost!='' && publicport!='' && privateport!='') {"
#	echo " 		window.location='nat_edit?vserver&proto='+proto+'&publichost='+publichost+'&publicport='+publicport+'&privatehost='+privatehost+'&privateport='+privateport+'&chain='+chain+'&ruleno='+num+'$"$server_sid"';"
#	echo " } else {"
#	echo "	alert('`$gettext_cmd "Please Fill All Fields"`');"
#	echo " } }"
	echo "function edit_dynamic(chain,num) {alert(\"`$gettext_cmd "Under Contruction"`\")}"
#	echo " proto=document.getElementById('d_proto').value;"
#	echo " src_ip=document.getElementById('src_ip').value;"
#	echo " src_port=document.getElementById('src_port').value;"
#	echo " dst_ip=document.getElementById('dst_ip').value;"
#	echo " dst_port=document.getElementById('dst_port').value;"
#	echo " map_ip=document.getElementById('map_ip').value;"
#	echo " if (proto!='' && src_ip!='' && dst_ip!='' && map_ip!='') {"
#	echo " 		window.location='nat_edit?dynamic&proto='+proto+'&src_ip='+src_ip+'&src_port='+src_port+'&dst_ip='+dst_ip+'&dst_port='+dst_port+'&map_ip='+map_ip+'&chain='+chain+'&ruleno='+num+'$"$server_sid"';"
#	echo " } else {"
#	echo "	alert('`$gettext_cmd "Please Fill All Fields"`');"
#	echo " } }"
	echo "</script>"
	echo " "
	${fw_cmd} -t nat -L --line-numbers -v -n | $sed_cmd /^$/d | ${awk_cmd} -f nat-edit -v edit_nat=$action 2>&1

	#=================
	#== Send footer ==
	#=================
	./footer
	;;
esac
