#!/usr/bin/awk -f
BEGIN {
	FIELDWIDTHS="19 19 6 7 9 7 7"
	route=ENVIRON["route"]
	sid=ENVIRON["server_sid"]
}
{
 dest	= $1;
 gw	= $2;
 flags	= $3;
 refs	= $4;
 use	= $5;
 netif	= $6;
 expire	= $7;
 gsub(/\ /,"",dest);
 gsub(/\ /,"",gw);
 gsub(/\ /,"",flags);
 gsub(/\ /,"",refs);
 gsub(/\ /,"",use);
 gsub(/\ /,"",netif);
 gsub(/\ /,"",expire);
 if ($1!~/^[A-Z]/ && $1!="") {
	if (NR %2 == 0) print "<tr class=a1>"
	else print "<tr class=a2>"
	if (dest==route) {
		print "<td class=editdelete><a href='JavaScript:apply(\""dest"\")'><img src='images/menu_addrule.png' width=20 height=20 align=top border=0></td>"
		print "<td><input type=\"text\" name=\"dest\" id=\"dest\" size=15 maxlength=20 value=\""dest"\"></td>"
		print "<td><input type=\"text\" name=\"gw\" id=\"gw\" size=15 maxlength=15 value=\""gw"\"></td>"
		print "<td>auto</td><td>auto</td>"
		print "<td class=editdelete><img src='images/eraser_static.png$"sid"' width=20 height=20 align=top border=0></td></tr>"
	} else {
		if (gw!~/\./) {
			print "<td class=editdelete><img src='images/editor_static.png$"sid"' width=20 height=20 align=top border=0></td>"
		} else {
			print "<td class=editdelete><a href='rt_edit?"dest"$"sid"'><img src='images/editor.png' width=20 height=20 align=top border=0></a></td>"
		}
		print "<td>"dest"</td><td>"gw"</td><td>"flags"</td><td>"netif"</td>"
		print "<td class=editdelete><a href='JavaScript:rt_del(\""dest"\")'><img src='images/eraser.png' width=20 height=20 align=top border=0></a></td></tr>"
	}
 }
}
